<?php
    date_default_timezone_set('America/Fortaleza');
    $hoje = date('d/m/Y \à\s H:i:s');

?>
<html>
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<h1 class="text-center"> Relatório de Cursos</h1>        
        <hr>
        <table  class="container table table-striped table-hover mt-4">
        <thead class="table-dark" style="border-bottom:1px solid black" >
        <tr>
                
                <th>#ID</th>
                <th>Nome</th>  
                <th>Descrição</th>
                <th>Categoria</th>
            </tr>
        </thead>
        <tbody>
        <?php
                // if(isset($alunos) && sizeOf($alunos) > 0){
                    foreach ($cursos ?? [] as $curso) {
                        echo "
                            <tr>
                            <td>{$curso['curso_id']}</td>
                            <td>{$curso['curso_nome']}</td>
                            <td>{$curso['curso_descricao']}</td>
                            <td>{$curso['categoria_nome']}</td>
                            </tr>
                        ";
                    }
                // }
            ?>
        </tbody>
        </table>
        <p class="text-center" > Gerado em <?php echo $hoje; ?></p>
</body>
</html>